### ISSUE TITLE
No input-placeholder mixin in compass/css3/user-interface

### ISSUE THREAD

**Issue by dsteinbach** [Igosuki/compass-mixins#74] opened 2015-11-06 18:10 UTC
The latest has it but this package doesnt :(

https://github.com/Compass/compass/blob/stable/core/stylesheets/compass/css3/_user-interface.scss

**Comment by xiaoDC** [comment] 2015-12-03 02:38
me too!I have the same problem !

**Comment by phazei** [comment] 2016-02-01 21:47
Duplicate of https://github.com/Igosuki/compass-mixins/issues/47

**Comment by xzyfer** [comment] 2016-05-19 07:29
Fixed in v0.12.9

**Closed by xzyfer** 2016-05-19 07:29 UTC
